# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run short tests
      run: go run -v main.go -run-tests -run-evals -run-all-tests -run 10 -exit-on-fail
    - name: Run medium tests
      run: go run -v main.go -run-tests -run-evals -run-all-tests -run 1000000 -exit-on-fail
    - name: Run long tests
      run: go run -v main.go -run-tests -run-evals -run-all-tests -run 250000000 -exit-on-fail
